apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: mdeployment.kb.io
    namespaceSelector:
      matchLabels:
        skycluster.io/app-scope: distributed
