# This rule is not used by the project skycluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over policy.skycluster.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: skycluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: policy-deploymentpolicy-admin-role
rules:
- apiGroups:
  - policy.skycluster.io
  resources:
  - deploymentpolicies
  verbs:
  - '*'
- apiGroups:
  - policy.skycluster.io
  resources:
  - deploymentpolicies/status
  verbs:
  - get
