---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster.io
  resources:
  - atlas
  - atlasmeshes
  - devicenodes
  - ilptasks
  - images
  - instancetypes
  - latencies
  - providerprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster.io
  resources:
  - atlas/finalizers
  - atlasmeshes/finalizers
  - devicenodes/finalizers
  - ilptasks/finalizers
  - images/finalizers
  - instancetypes/finalizers
  - latencies/finalizers
  - providerprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster.io
  resources:
  - atlas/status
  - atlasmeshes/status
  - devicenodes/status
  - ilptasks/status
  - images/status
  - instancetypes/status
  - latencies/status
  - providerprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies
  - deploymentpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/finalizers
  - deploymentpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/status
  - deploymentpolicies/status
  verbs:
  - get
  - patch
  - update
