---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - skyxrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - skyxrds/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - skyxrds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.skycluster.io
  resources:
  - devicenodes
  - ilptasks
  - images
  - instancetypes
  - latencies
  - providerprofiles
  - skyclusters
  - skynets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.skycluster.io
  resources:
  - devicenodes/finalizers
  - ilptasks/finalizers
  - images/finalizers
  - instancetypes/finalizers
  - latencies/finalizers
  - providerprofiles/finalizers
  - skyclusters/finalizers
  - skynets/finalizers
  verbs:
  - update
- apiGroups:
  - core.skycluster.io
  resources:
  - devicenodes/status
  - ilptasks/status
  - images/status
  - instancetypes/status
  - latencies/status
  - providerprofiles/status
  - skyclusters/status
  - skynets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies
  - deploymentpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/finalizers
  - deploymentpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.skycluster.io
  resources:
  - dataflowpolicies/status
  - deploymentpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps
  - skyproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps/finalizers
  - skyproviders/finalizers
  verbs:
  - update
- apiGroups:
  - svc.skycluster.io
  resources:
  - skyapps/status
  - skyproviders/status
  verbs:
  - get
  - patch
  - update
