apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/policy.skycluster.io_dataflowpolicies.yaml
- bases/policy.skycluster.io_deploymentpolicies.yaml
- bases/core.skycluster.io_skyclusters.yaml
- bases/core.skycluster.io_ilptasks.yaml
- bases/core.skycluster.io_atlass.yaml
- bases/svc.skycluster.io_skyproviders.yaml
- bases/core.skycluster.io_images.yaml
- bases/core.skycluster.io_instancetypes.yaml
- bases/core.skycluster.io_providerprofiles.yaml
- bases/core.skycluster.io_devicenodes.yaml
# - ../webhook
- ../webhook-local
- bases/core.skycluster.io_latencies.yaml
- bases/core.skycluster.io_skynets.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# - path: patch/patch-object-simplify-validation.json
#   target:
#     group: apiextensions.k8s.io
#     kind: CustomResourceDefinition
#     name: skynets.core.skycluster.io
#     version: v1

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
